language: python
matrix:
  include:
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -U Cython
- pip install -U numpy
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: heuro-labs
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: NvkKj4kUjbLIz+1xOp8v5qYnGBbpX3YB+iJ2SRXRiiJVuHNqFuorZtl8dXqZfHf7VoFs39Tx5lzhUS0yH9/dzy4LOHP6tgGL2IdiWc7a0eDLVhFOYwpY6JFE+mhYTNM1oaOjn7fwAG6eufmJ9RTV42UZ6lbZPHRH295nsgUk2HSiGaH8oCRLrJml1L7DzBbbNTozWhKYVDTiLQdW53ESo2rqkSPCIhD1an+EMSNLaPEcgvwWgmnt6MGYvDwvARuYPoPTspxux+dj42Sdb0RtRFjg66naU7sHTpPa/q9xvOG3lwaXYpqMjd/BdQmW4j2nB4fV+H0dTB/N7DcwRJBSHpTCvpxmh9ghI2jg11MDkhnBYiMcTJtwz/ZZ25oP1AugZzEl4MG+/DYKbSdF4s5flBhpJyjT+Je2U4WdoF87E2gxWwUCzGxv3OD9Uzo7Va3/ceD20xmK0IHPNusg/quszoZfON2exflhBxPfKck2Usto1sAcIwQwC4hlqQKkHKuvI4K3Tw4a//2r1tEjAiFpx2xPxl7I1J848aawDky7Dm+dcxcRS3GJKZ2V+EzGMX/CMRbwK5GNruBHlvUKv0n2zRdFCZ+WBmPZYMWSRiyIaaReCFonn/6APDlPFzj8EJ3nWjBgpqlvAQ348Tf7CkY5u21DMcjMvVkNY3k29gnoPOw=
