# Config file for automatic testing at travis-ci.com

language: python
matrix:
    include:
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install -U tox-travis
script: tox
